### ISSUE TITLE
Two Factor Authentication Settings

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL-Design#38]
Related Issue: https://github.com/Ride-The-Lightning/RTL/issues/210
Related to PR: https://github.com/Ride-The-Lightning/RTL/pull/266

Login input validation:
![image](https://user-images.githubusercontent.com/23240721/76008547-d1de1f80-5edd-11ea-80f7-6aa5731a9e62.png)

Login response validation:
![image](https://user-images.githubusercontent.com/23240721/76008216-43699e00-5edd-11ea-82ab-a02dd00ea82d.png)

Enable 2FA Settings (Laptop view):
![image](https://user-images.githubusercontent.com/23240721/76008633-f2a67500-5edd-11ea-970b-5393d1b0b34d.png)

Enable 2FA Settings (Mobile view):
![image](https://user-images.githubusercontent.com/23240721/76008424-a0655400-5edd-11ea-8211-56a88357a9c1.png)

Disable 2FA Settings:
![image](https://user-images.githubusercontent.com/23240721/76008613-eb7f6700-5edd-11ea-819f-f4a0c79440b7.png)

**Comment by rbndg** [comment]
Great job on this!

**Comment by diogorsergio** [comment]
Design addressed in Pull-Request: https://github.com/Ride-The-Lightning/RTL-Design/pull/41

**Summary:** 
Enabling and disabling two-factor authentication flows. Used the stepper for consistency, since this would be a multi-step process for both cases.

**Enable:**

-    Step1: Authenticate with RTL password
-    Step2: Scan or copy the code
-    Step3: Verify with OTP input.

**Disable:**

 -   Step1: Authenticate with RTL password
 -   Step2: Disable confirmation

Check PR for more information.
